name: PDF Question Answering Github Actions

on:
  pull_request:
    branches: ["main", "development"]
    paths-ignore:
      - README.md

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    strategy:
      matrix:
        python-version: [3.11.2]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Running Test Cases
        run: |
          python app.py
          pytest tests/test_app.py
