name: PDF Question Answering Github Actions

on:
  pull_request:
    branches: ["development"]
    paths-ignore:
      - README.md
  push:
    branches: ["development"]
    paths-ignore:
      - README.md

permissions:
  id-token: write
  contents: read

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    env:
      POSTGRESQL_URL_DATABASE: ${{secrets.POSTGRESQL_URL_DATABASE}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.2"

      - name: Installing Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Start FastAPI server
        run: |
          nohup python3 uvicorn app:app --host ${{secrets.HOST}} --port 8000 &
        # Wait a moment for the server to start
        timeout-minutes: 2

      - name: Run Tests
        run: |
          pytest tests/test_app.py
